### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by frederikhors** [roxiness/routify#168]
Windows 10, node `v12.16.3`, npm `6.14.4`, fresh new `routify init` and `npm run build` with no edits:

```bash
PS C:\switch_routify>npm run build

> svelte-app@1.0.0 build C:\switch_routify
> routify -bD && rollup -c

[Routify] Generated routes

src/main.js → dist/build/bundle.js...
created dist/build/bundle.js in 12.2s

src/main.js → dist/build...
created dist/build in 9.9s

> svelte-app@1.0.0 export C:\switch_routify
> routify export

[Routify] Exporting to: dist
(node:12300) UnhandledPromiseRejectionWarning: TypeError: A.getTotalLength is not a function
(node:12300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Routify] Generated 25 static pages
[Routify] Export finished
[Routify] Build can be served from ./dist and is ready to be deployed
```

**Comment by jakobrosenberg** [comment]
Thank you @frederikhors . I'll have a look at this. Looks like one of the 25 pages didn't get prerendered.

**Comment by jakobrosenberg** [comment]
This should be fixed in v1.6.5
