### ISSUE TITLE
build script: Error: Cannot find module 

### ISSUE THREAD

**Issue by jadbox** [roxiness/routify#223]
I'm working on a fairly new project, and I'm getting two odd issues. The `build` script gives the below error is the first issue. It's odd as the bundle.js file is located in the correct directory so I'm not sure why it cannot be found.

I'm not sure if this is related, but when I call SSR in the browser it just loads forever and times out. There's no errors in the `npm run dev` log, and is says spassr is running ssr on http://localhost:5005.

```node version: 14.4.0```
```routify 1.8.0 official release```

`yarn run build`
```
> svelte-app@1.0.0 routify /home/jdunlap/github/abridged/unroll
> routify -D "-b"

[Routify] Generated routes in 0 ms

src/main.js → dist/build...
created dist/build in 2.2s

src/main.js → dist/build/bundle.js...

> svelte-app@1.0.0 export /home/jdunlap/github/abridged/unroll
> routify export && cp dist/__app.html dist/404.html

[Routify] Exporting to: dist
(node:12129) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/jdunlap/github/abridged/unroll/dist/build/bundle.js'
Require stack:
- /home/jdunlap/github/abridged/unroll/node_modules/@sveltech/routify/lib/services/exporter.js
- /home/jdunlap/github/abridged/unroll/node_modules/@sveltech/routify/plugins/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.resolve (internal/modules/cjs/helpers.js:79:19)
    at saveUrls (/home/jdunlap/github/abridged/unroll/node_modules/@sveltech/routify/lib/services/exporter.js:24:44)
    at exporter (/home/jdunlap/github/abridged/unroll/node_modules/@sveltech/routify/lib/services/exporter.js:17:11)
    at Command.<anonymous> (/home/jdunlap/github/abridged/unroll/node_modules/@sveltech/routify/plugins/cli.js:77:5)
    at Command.listener [as _actionHandler] (/home/jdunlap/github/abridged/unroll/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/home/jdunlap/github/abridged/unroll/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/home/jdunlap/github/abridged/unroll/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/home/jdunlap/github/abridged/unroll/node_modules/commander/index.js:882:12)
    at Command.parse (/home/jdunlap/github/abridged/unroll/node_modules/commander/index.js:717:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
created dist/build/bundle.js in 2s

src/sw.js → dist/sw.js...
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1593572819615-0.12942914595977295/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> svelte-app@1.0.0 export /home/jdunlap/github/abridged/unroll
> routify export && cp dist/__app.html dist/404.html

[Routify] Exporting to: dist

The service worker file was written to dist/sw.js
The service worker will precache 17 URLs, totaling 651 kB.

created dist/sw.js in 1.4s
Done in 10.28s.
```

**Comment by jadbox** [comment]
Also I'm using the standard rollup.config.js and package.json from the routify starter.

**Comment by jakobrosenberg** [comment]
Hi @jadbox, do you get the error with npm?

Just to rule out yarn as the cause, could check port 5005 after running the following?
```
npx @sveltech/routify init
npm run dev
```

**Comment by jadbox** [comment]
Hey @jakobrosenberg , for testing I deleted node_modules and started again with just `npm` instead of yarn, but there was no difference in behavior. I still get the bundle.js error on build and `npm run dev` ssr running on 5005 fails with a timeout.

If you like the test, you can check out the project here on `wip2` branch.
https://github.com/abridged/unroll/tree/wip2

**Comment by jakobrosenberg** [comment]
Did you copy the rollup.config.js and package.json from the starter template or are you using the actual template?

**Comment by jakobrosenberg** [comment]
I've tracked the error down to your EthersComp.svelte, which contains:

```html
{#if show}
    <slot/>
{/if}
```

Since EthersComp is wrapped around the layouts/page chain of Routify, the `if` condition prevents the page from being loaded. 

As SSR waits for the last page to be loaded before it renders to HTML, it's waiting indefinitely.

You can either
1. Redirect to a login/guest page.
2. Call the `$ready` helper on EthersComp to render the page instantly.

I'm on Discord if you want some feedback on options. :)

**Comment by jadbox** [comment]
@jakobrosenberg ah okay, I got SSR working now with your help. I'm still getting the build bundle.js error though on `npm run build`. I'll also jump on discord.

I copied the rollup and package.json from the starter template.

**Comment by jadbox** [comment]
Closing for now as I think I'm passed this now and lots of build stuff has changed since this bug
